# Header

menu:
  主页: /
  B站: https://space.bilibili.com/1989702333
  下载: /blacktech-nav/
  教程: /资源合集-1/
  进群: http://www.python4office.cn/wechat-group/
#  开源项目: /tags/开源项目/

# SubNav
subnav:
  github: "https://github.com/CoderWanFeng/python-office"
  weibo: "https://weibo.com/u/7726957925"
  # rss: "#"
  zhihu: "https://www.zhihu.com/people/cheng-xu-yuan-wan-feng-31"
  qq: "http://www.python4office.cn/images/qq.jpg"
  weixin: "https://mp.weixin.qq.com/s/aejZx5fWAFRTuYutB9JheQ"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://www.bilibili.com/video/BV1pT4y1k7FH"
  acfun: "https://www.acfun.cn/u/35901274"
  mail: "http://www.python4office.cn/images/CoderWanFeng.jpg"
#  facebook: "https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzUzNTc5NjA4NQ==&action=getalbum&album_id=2188859340688785417&subscene=126&scenenote=https%3A%2F%2Fmp.weixin.qq.com%2Fs%3F__biz%3DMzUzNTc5NjA4NQ%3D%3D%26mid%3D2247493383%26idx%3D1%26sn%3D38a3be8590eb3e2032634a16ca657801%26chksm%3Dfa82a71dcdf52e0b4cf435fbaace63b8eaf02f1fabea222738dff8929b4563fc5d9cf3cef761%26scene%3D126%26sessionid%3D1648790415%26key%3D669b48136b291a4e8b24f266d14e032caf9e11699d61a27027bb16741edd1f1c39fd5591b79c1dd351815c132d72fee2aa3ffdc0915b6b39ff84ac02c70e6a061f4cdf3e5051b938aedc6e7641f4157d0569ac6d954263ba79aac5b05e19703be0bed67347b3153e6170befa479cfa6084376648bce67f7e7f3c6c1ed68d9f16%26ascene%3D15%26uin%3DMzYwNDYzMjE5OQ%253D%253D%26devicetype%3DWindows%2B10%2Bx64%26version%3D63060012%26lang%3Dzh_CN%26exportkey%3DAYaTIXvIqSp9X5NJ45NnaOg%253D%26acctmode%3D0%26pass_ticket%3DXQ8A%252B%252B3thnoPOXO6HUboeWmiUBas1vk2ASbJfW%252B8vCH1PJv63WAUVRvjp6BjayR0%26wx_header%3D0%2&nolastread=1&uin=&key=&devicetype=Windows+10+x64&version=63060012&lang=zh_CN&ascene=15&session_us=gh_cc51d9646440&fontgear=2"
  google: "https://curl.qcloud.com/rRyNNRRE"
#  twitter: "https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzUzNTc5NjA4NQ==&action=getalbum&album_id=2188859340688785417&subscene=126&scenenote=https%3A%2F%2Fmp.weixin.qq.com%2Fs%3F__biz%3DMzUzNTc5NjA4NQ%3D%3D%26mid%3D2247493383%26idx%3D1%26sn%3D38a3be8590eb3e2032634a16ca657801%26chksm%3Dfa82a71dcdf52e0b4cf435fbaace63b8eaf02f1fabea222738dff8929b4563fc5d9cf3cef761%26scene%3D126%26sessionid%3D1648790415%26key%3D669b48136b291a4e8b24f266d14e032caf9e11699d61a27027bb16741edd1f1c39fd5591b79c1dd351815c132d72fee2aa3ffdc0915b6b39ff84ac02c70e6a061f4cdf3e5051b938aedc6e7641f4157d0569ac6d954263ba79aac5b05e19703be0bed67347b3153e6170befa479cfa6084376648bce67f7e7f3c6c1ed68d9f16%26ascene%3D15%26uin%3DMzYwNDYzMjE5OQ%253D%253D%26devicetype%3DWindows%2B10%2Bx64%26version%3D63060012%26lang%3Dzh_CN%26exportkey%3DAYaTIXvIqSp9X5NJ45NnaOg%253D%26acctmode%3D0%26pass_ticket%3DXQ8A%252B%252B3thnoPOXO6HUboeWmiUBas1vk2ASbJfW%252B8vCH1PJv63WAUVRvjp6BjayR0%26wx_header%3D0%2&nolastread=1&uin=&key=&devicetype=Windows+10+x64&version=63060012&lang=zh_CN&ascene=15&session_us=gh_cc51d9646440&fontgear=2"
  linkedin: "https://www.bilibili.com/video/BV1Nr4y1B76X"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# visitors count
counter: true

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '赞赏后，请添加微信：CoderWanFeng，我送你一次1v1的学习咨询'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay:
# 微信二维码图片地址
weixin: http://www.python4office.cn/images/wechat-pay.jpg
# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: 'a8a4322ff49ea1111171ed84ea70baa6'
google_analytics: ''
favicon: https://pic3.zhimg.com/v2-4d368514cb16353edc1a21530c5ea941_xl.jpg?source=32738c0c

#你的头像url
avatar: https://pic3.zhimg.com/v2-4d368514cb16353edc1a21530c5ea941_xl.jpg?source=32738c0c

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
#changyan_appid: 'cyvOjMKDi'
#changyan_conf: 'e7a3f9de2303b2e519315ab135318536'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于作者'

friends:
  交流群: http://python4office.cn/wechat-group/
  资源合集: https://blog.csdn.net/weixin_42321517
  云服务器: https://www.aliyun.com/minisite/goods?userCode=t6duaoe1
  数据分析: https://t2.lagounews.com/TRAERVR8sp986
  自动化办公: http://gk.link/a/10E3B
  HelloCode.: https://www.hellocode.top

aboutme: 985硕士，Python程序员，业余自媒体人<br><br>定居重庆<br><br>努力分享有价值的内容<br><br>我的微信：CoderWanFeng，技术/自媒体/合作/约饭<br><br>社区交流群：http://python4office.cn/wechat-group/
