sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public

  # https://travis-ci.com/github/zhaofeng092/zhaofeng092.github.io/settings
  # https://hexo.io/zh-cn/docs/github-pages.html